#!/usr/bin/env bash

platform_options="local gcp aws iris"

usage() {
printf "
Usage: sudo %s -p PLATFORM
Options:
 -p                 Platform that we are running the scripts on
Platforms (-p):
  local             Used when running on a local VM
  aws               AWS
  gcp               Google Cloud Platform
  iris              Used when running within iris
\n" "${0}";
exit 1;
}
contains() { [[ ! -z "${2}" && "${1}" =~ (^|[[:space:]])${2}($|[[:space:]]) ]] && return 0  || return 1; }

if [[ $1 == "" ]]; then
  usage;
else

  while getopts ":p:" opt
  do
      case "${opt}" in
          "p")
              p=${OPTARG}
              contains "${platform_options}" "${p}" || usage
              ;;
          ":")
              printf "\nError: Option ${OPTARG} requires an argument\n"
              usage
              exit 1
              ;;
          "?")
              printf "\nError: Unknown option -$OPTARG \n"
              usage
              exit 1
              ;;
          *)
              usage
              exit 1
              ;;
      esac
  done

  shift $((OPTIND-1))

fi

if ! type "ansible" > /dev/null 2>&1; then
  echo "Need to Install Ansible"


  OS=$(cat /etc/os-release | grep "^ID=" | cut -d'=' -f2 | tr -d '"')

  echo "Current Platform: $p"
  echo "Current OS:       $OS"

  case $p in
       local)
           repo='epel'
           if [[ $OS == 'rhel' ]] 
           then
             echo "rhel in a local VM"
           elif [[ $OS == 'centos' ]]
           then
             epel_exists=$(yum repoinfo $repo | grep 'Repo-id' -c)
             if [[ $epel_exists = 0 ]]
             then
               yum install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm -y
               yum install --enablerepo=$repo ansible -y
             fi
           fi
           ;;
       gcp)
           repo='???'
           yum install ansible -y
           ;;
       aws)
           repo='???'
           ;;
       *)
  esac
else
  echo "Ansible already installed"
fi  
   

